quarkus.application.name=spring-vs-quarkus

# Workaround for Java 25 + Byte Buddy compatibility
quarkus.native.additional-build-args=-Dnet.bytebuddy.experimental=true
quarkus.http.port=8080
quarkus.http.limits.max-body-size=10M
quarkus.http.limits.max-form-attribute-size=10M
quarkus.http.limits.max-form-fields=256

# Jackson
quarkus.jackson.fail-on-unknown-properties=false

# Logging
quarkus.log.level=INFO
quarkus.log.category."io.snowdrop".level=DEBUG
